service: serverlessapi #Name of your App

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x # Node JS version
  memorySize:
  timeout: 128
  stage: production
  region: us-east-1 # AWS region

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /

disabledDeprecations:
  - "*" # To disable all deprecation messages
